package ExceptionHandling;

import java.util.Scanner;

public class TryWithResourseRunner {

	public static void main(String[] args) {
		Scanner scanner = new Scanner(System.in);
			scanner = new Scanner(System.in);
			int[] numbers = { 12, 3, 4, 5 };

			int number = numbers[5];

		System.out.println("Just before closing out main");
	}

}
